name: Sendu-fp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            choco install nsis
          fi

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Build the Tauri app
        run: cargo tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-build
          path: ./src-tauri/target/release/bundle/
